Feature/feed#22
buddy-ya/be pull request #23
Opened 2024-11-21 01:15 UTC by mangsuyo

## 📌 관련 이슈
[피드 기능 개발 #22](https://github.com/buddy-ya/be/issues/22)
<br><br>

## 🛠️ 작업 내용
- Feed 및 관련 Entity 구현 (Feed, Category, Like, Bookmark)
- 피드 목록 조회/상세 조회/생성/수정/삭제 API 구현
- 피드 조회시 Page 처리를 통한 피드 목록 페이지네이션 구현 

피드에 `댓글`, `좋아요 및 북마크`, `사진 파일`에 대한 부분은 다음 PR에 구현하겠습니다.
<br><br>

## 🎯 리뷰 포인트
- 코드 컨벤션이 잘 지켜졌는가?
- 예외처리가 빠진 부분은 없는가?
- 조회의 경우 조회를 한 곳에서 `Optional` 예외처리를 하지않고 
해당 도메인의 서비스 계층에서 `findBy-` 메서드를 제공하여 예외처리 코드의 중복 방지.
- 메서드안에서 개행을 하지못하므로 메서드가 길어졌을 때 분리하여 가독성을 높임. 
<br><br>
## 🤔 고민한 점
### 페이지네이션 구현 배경
- 게시글이 50개만 넘어가도 프론트엔드 렌더링 성능에 영향이 있을 것으로 판단
- Spring Data JPA의 페이징 기능을 활용하여 10개씩 피드 목록 반환하도록 구현
- 저희 게시글은 조회 기준에 카테고리가 있기 때문에, `Pageable` 로 요청을 받기에는 제한이 있었습니다.
따라서 카테고리 필드가 담긴 `RequestDTO`를 만들어 요청을 처리했습니다.

### 논의하고 싶은 점
- `Repositroy`에서 조회 기능을 수행하면 `Optional`객체가 반환되기 때문에, 요청한 쪽에서 반드시 예외처리를 해야합니다.
-  조회의 경우 해당 서비스 계층에서 예외처리까지 진행하고 조회된 객체를 반환하는 메서드를 제공하는건 어떨까요?
<br><br>

## 📎 커밋 범위 링크

<br><br>

2024-11-21 08:54 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/service/FeedService.java
> +        return feedRepository.findById(feedId).orElseThrow(() -> new FeedException(FeedExceptionType.FEED_NOT_FOUND));
P3: 메서드 체이닝이 길어지면 다음과 같이 구분해 주는 것도 괜찮을 것 같아요~
```suggestion
        return feedRepository.findById(feedId)
                             .orElseThrow(() -> new FeedException(FeedExceptionType.FEED_NOT_FOUND));
```

2024-11-21 09:02 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/controller/FeedController.java
> +    }
P2: feedUpdatedRequest를 확인해보니 title, content, category만 수정하는 것 같은데 feed의 전체 수정이 아닌 부분 수정은 RestAPI상 PUT보다 PATCH를 사용하는 것은 어떤가요?

2024-11-21 09:06 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/domain/Feed.java
> +import com.team.buddyya.common.domain.BaseTime;
P2: 컨벤션 상 import문 붙이는 게 좋아보여요!

2024-11-21 09:08 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/domain/Comment.java
> +
내용이 많을 수 있는 content의 경우 디폴트 값인 VARCHAR 대신 TEXT로 타입 명시해주는 것 좋네요!! 💯

2024-11-21 09:44 UTC, maark1106 requested changes
전반적으로 컨벤션이 잘 지켜진 것 같고 가독성도 괜찮아 코드 흐름도 이해하기 편했던 것 같아요~ 
논의하고 싶은 점에 대한 생각입니다.
처음에 Repository에서 바로 조회하여 예외 처리를 해주는 것에 대해 별 생각없이 사용하다가 어느 순간 반복 작업을 하고 있다고 느꼈습니다
그리고 해당 도메인의 예외를 다른 도메인에서 처리해도 되나라는 고민도 했었던 것 같습니다
명수님 말씀대로 `서비스 계층에서 예외처리까지 진행하고 조회된 객체를 반환하는 메서드`로 리팩토링을 진행해도 좋을 것 같습니다

2024-11-21 09:44 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/dto/response/FeedCreateResponse.java
> +) {
P3: 컨벤셩 상 record의 필드 하나인 경우 
```suggestion
public record FeedCreateResponse(Long id) {
}
```
이렇게 통일하기로 했어요!

2024-11-21 09:44 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/service/FeedService.java
> +    }
페이지네이션하는 코드가 익숙하지 않아서 찾아봤는데 페이지 번호, 페이지 크기로 피드 목록을 잘라서 가져오는 거군요!  페이징 처리 잘 적용하신 것 같아요~ 배워갑니다! 👍

2024-11-21 09:44 UTC, maark1106 commented on src/main/java/com/team/buddyya/feed/service/FeedService.java
> +    }
feed 예전에 구현했을 때 여러 게시물 api마다 좋아요, 북마크 여부를 일일이 넣어줘서 번거로웠는데 `getUserAction`으로 재사용하는 것 좋네요 👍

2024-11-21 14:34 UTC, sangu1026 commented on src/main/java/com/team/buddyya/feed/controller/FeedController.java
p3: create 그리고 update 후에 응답값에 생성된 게시물에 대한 정보를 포함하지 않으셨네요.
create같은 경우에 생성후에피드 목록으로 리다이렉트되면 생성된 게시물에 대한 정보가 필요없을 거 같은데,
update 같은 경우에 수정 후 목록으로 리다이렉트 되기보다 수정된 피드를 즉각적으로 
보여주는 것이 낫지 않을까요? 그래서 저는 update같은 경우에 update후 응답값으로 수정된 피드를
반환해주는 것이 나을 거 같아요. 그렇지 않으면 유저가 수정된 피드를 확인하기 위해서 한번 더 getFeeds를
호출해야되기 때문입니다.

2024-11-21 14:45 UTC, sangu1026 commented
전반적으로 코드 컨벤션도 잘 지켜지고 메서드가 하나의 역할을 하도록 잘 분리시키신 것 같아요 👍 

저도 온보딩할 때 명수님과 같이Repositroy에서 조회 기능을 수행할때 다른 서비스에서 직접 예외를 처리할지
아니면 따로 서비스를 만들어서 해당 도메인에서 예외 처리할지 고민하다가 단순 조회느낌이어서 따로 분리하진 않았습니다.

그런데 다시 생각해보니 추후에 조회하는 기능이 다른 서비스에서도 사용될 수 있다는 점에서 조회의 경우 
해당 서비스 계층에서 예외처리까지 진행해서 객체를 반환하는 것이 더 나을 것 같네요. 
저도 반영 및 수정해서 다시 올리도록 하겠습니다!

수고하셨습니당~~ 👏 👏

2024-11-22 08:10 UTC, mangsuyo commented on src/main/java/com/team/buddyya/feed/service/FeedService.java
> +        return feedRepository.findById(feedId).orElseThrow(() -> new FeedException(FeedExceptionType.FEED_NOT_FOUND));
네 컨벤션이 어긋난 부분이 있었네요.
수정하겠습니다!

2024-11-22 08:11 UTC, mangsuyo commented on src/main/java/com/team/buddyya/feed/controller/FeedController.java
> +    }
네 맞는 말씀입니다. `patch`로 변경하겠습니다!

2024-11-22 08:12 UTC, mangsuyo commented on src/main/java/com/team/buddyya/feed/domain/Feed.java
> +import com.team.buddyya.common.domain.BaseTime;
`우아한테크코스 xml`로 인한 `import static`과의 개행입니다!

2024-11-22 08:12 UTC, mangsuyo commented on src/main/java/com/team/buddyya/feed/dto/response/FeedCreateResponse.java
> +) {
네 알겠습니다!

2024-11-22 08:15 UTC, mangsuyo commented on src/main/java/com/team/buddyya/feed/controller/FeedController.java
이미 단일 피드를 조회하는 `getFeed`가 있기 때문에,
프론트측에서도 업데이트된 피드인지에 대한 상태관리 고민 없이 상세 피드로 들어왔을 때 `getFeed` api를 일관되게 요청하는 것이 
더 깔끔하다고 생각했습니다!

2024-11-22 10:25 UTC, sangu1026 commented on src/main/java/com/team/buddyya/feed/controller/FeedController.java
API 호출 수를 줄이는 것을 위주로 생각했었는데, 명수님의 말을 들어보니
이렇게 하면 수정은 수정 작업에 피드를 가져오는 것은 가져오는 것에 
각각 집중할 수 있어 더 좋은거 같네요 👍

2024-11-22 10:25 UTC, sangu1026 approved these changes

2024-11-22 11:48 UTC, maark1106 approved these changes

2024-11-22 11:56 UTC, merged